### ISSUE TITLE
Failed to run MovSimcore

### ISSUE THREAD

**Issue by mauricionovaes** [movsim/movsim#33]
I'm trying  to run movsim core using Eclipse , but there is a problem with some dependencies . How can I fix this?

Description	Resource	Path	Location	Type
Missing artifact org.movsim:MovsimCommon:jar:1.6.0-SNAPSHOT	pom.xml	/MovsimCore	line 19	Maven Dependency Problem
Missing artifact org.movsim:MovsimConsumption:jar:1.6.0-SNAPSHOT	pom.xml	/MovsimCore	line 24	Maven Dependency Problem
Missing artifact org.movsim:MovsimXsd:jar:1.6.0-SNAPSHOT	pom.xml	/MovsimCore	line 14	Maven Dependency Problem
The container 'Maven Dependencies' references non existing library 'C:\Users\.m2\repository\org\movsim\MovsimXsd\1.6.0-SNAPSHOT\MovsimXsd-1.6.0-SNAPSHOT.jar'	MovsimCore		Build path	Build Path Problem
The project cannot be built until build path errors are resolved	MovsimCore		Unknown	Java Problem

**Comment by akegermany** [comment]
The build is OK: https://travis-ci.org/movsim/movsim
You have to compile all submodules of course
