### ISSUE TITLE
Errors in POM files 

### ISSUE THREAD

**Issue by jijizar** [movsim/movsim#34]
During the installation
![filepom- movsim core](https://cloud.githubusercontent.com/assets/10086815/17778227/3c679726-655b-11e6-9468-d2b93a048413.png)
![pom-movsim common](https://cloud.githubusercontent.com/assets/10086815/17778228/3c6ce884-655b-11e6-897f-77510295195c.png)
![pom-movsim viewer](https://cloud.githubusercontent.com/assets/10086815/17778229/3c70abae-655b-11e6-85c7-d399c25cdd5d.png)

 I found some errors in the POM file level for each Common , Core, viewer folders

The POM file error for MOVsim Common is:

Failed to read artifact descriptor for org.jdom: jdom: jar: 1.1
org.eclipse aether

the POM file error MOVsim Core is:

Missing artifact org.movsim: MovsimXsd: jar: 1.6.0-SNAPSHOT

the POM file error MOVsim Viewer is:

Missing artifact org.movsim: MovsimXsd: jar: 1.6.0-SNAPSHOT

how to fix these errors?

Thanks

**Comment by akegermany** [comment]
The build is green and the pom files are (therefore) okay. 
I guess you missed to import the other submodule(s) in your IDE (xsd) since this is required as defined in the parent pom. Or try to build all dependencies for your local maven repository ("mvn install" in the main directory). This is what eclipse complains about.

**Comment by jijizar** [comment]
Thank you so for your reply
so , I follow same procedure to install Movsim via git, I have successfully attempted  to install Maven as the screen capture shows
my question is 
how I can make the execution of scenarios as IDM for example, or  if i want to develop another car Following model in movsim how to show the interface which visualise the traffic simulation  ??
![maven](https://cloud.githubusercontent.com/assets/10086815/17811848/7e165970-661c-11e6-9008-b78ed3ac54e9.png)

**Comment by akegermany** [comment]
Congratulations. You've built the software successfully. So, there is no error in the poms.
Please see the README.md in core/ and viewer/. You'll find the answer there. If not feed free to extend the documention for making the project better. 
I close the ticket as it is not a bug or built problem.
