### ISSUE TITLE
output files CSV Directory

### ISSUE THREAD

**Issue by HamdHD** [movsim/movsim#35]
Hi ,

By running the routing scenario simulation , we don't found the text files output CSV which contains the data. can you explain how to get it .

![xml](https://cloud.githubusercontent.com/assets/21281119/18030126/89e282a0-6ca3-11e6-8f14-6039c559f1a4.png)

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SCENARIO SYSTEM "multiModelTrafficSimulatorInput.dtd">

<SCENARIO network_filename="routing.xodr">
    <FUEL_CONSUMPTION>
        <CONSUMPTION_MODEL label="carDiesel" output="false">
            <CAR mass="1500" cross_section_surface="2.2" cd_value="0.32" electric_power="3000" const_friction="0.015" v_friction="0" dynamic_tyre_radius="0.31" />
            <ENGINE max_power_kW="90" cylinder_vol_l="1.4" idle_cons_rate_linvh="0.8" cspec_min_g_per_kwh="185" pe_min_bar="1" pe_max_bar="22" idle_rotation_rate_invmin="900" max_rotation_rate_invmin="4500">
                <GEAR_RATIOS>
                    <GEAR_RATIO phi="16.7" />
                    <GEAR_RATIO phi="10.1" />
                    <GEAR_RATIO phi="6.8" />
                    <GEAR_RATIO phi="5.0" />
                    <GEAR_RATIO phi="3.8" />
                    <GEAR_RATIO phi="3.1" />
                    <GEAR_RATIO phi="2.6" />
                </GEAR_RATIOS>
            </ENGINE>
        </CONSUMPTION_MODEL>
    </FUEL_CONSUMPTION>
    <VEHICLES write_fund_diagrams="false">
        <VEHICLE label="ACC1" length="6" b_max="40" consumption="carDiesel" width="4.4" reaction_time="0">
            <LONGITUDINAL_MODEL>
                <ACC v0="35" T="1.2" s0="2" s1="0" delta="4" a="1.2" b="2.0" coolness="1" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="true" crit_speed_eur="20">
                <MOBIL b_safe="20.0" s_min="2.0" threshold="0.1" bias_right="0." politeness="0.1" />
            </LANE_CHANGE_MODEL>
        </VEHICLE>
        
        <VEHICLE label="ACC2" length="16" b_max="40" consumption="carDiesel" width="4.4" reaction_time="0">
            <LONGITUDINAL_MODEL>
                <ACC v0="25" T="1.4" s0="2" s1="2" delta="4" a="0.8" b="2.0" coolness="1" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="true" crit_speed_eur="20">
                <MOBIL b_safe="20.0" s_min="2.0" threshold="0.2" bias_right="0.0" politeness="0.1" />
            </LANE_CHANGE_MODEL>
        </VEHICLE>
        <VEHICLE label="Obstacle" length="0" width="4.4" b_max="10000" reaction_time="0" consumption="none">
            <LONGITUDINAL_MODEL>
                <IDM v0="0" T="1" s0="2" a="1.0" b="1.5" s1="0" delta="4" />
            </LONGITUDINAL_MODEL>
            <LANE_CHANGE_MODEL eur_rules="false" crit_speed_eur="25" />
        </VEHICLE>
    </VEHICLES>
    <SIMULATION dt="0.2" duration="86400" fixed_seed="true" seed="42" crash_exit="false">
        <TRAFFIC_COMPOSITION>
            <VEHICLE_TYPE label="ACC1" fraction="0.7" relative_v0_randomization="0.2" route_label="" />
            <VEHICLE_TYPE label="ACC2" fraction="0.3" relative_v0_randomization="0.2" route_label="" />
        </TRAFFIC_COMPOSITION>
        <ROAD id="1" logging="false">
            <TRAFFIC_COMPOSITION>
                <VEHICLE_TYPE label="ACC1" fraction="0.7" relative_v0_randomization="0.2" route_label="" />
                <VEHICLE_TYPE label="ACC2" fraction="0.3" relative_v0_randomization="0.2" route_label="" />
            </TRAFFIC_COMPOSITION>
            <TRAFFIC_SOURCE logging="false">
                <INFLOW t="0" q_per_hour="0" v="20" />
                <INFLOW t="60" q_per_hour="1800" v="20" />
                <INFLOW t="120" q_per_hour="1800" v="20" />
                <INFLOW t="180" q_per_hour="0" v="20" />
            </TRAFFIC_SOURCE>
            <FLOW_CONSERVING_INHOMOGENEITIES>
                <INHOMOGENEITY x="0" alpha_T="0.8" alpha_v0="1" />
                <INHOMOGENEITY x="200" alpha_T="1." alpha_v0="1" />
            </FLOW_CONSERVING_INHOMOGENEITIES>
        </ROAD>
        <ROAD id="10" logging="false">
            <FLOW_CONSERVING_INHOMOGENEITIES>
                <INHOMOGENEITY x="250" alpha_T="1.5" alpha_v0="0.9" />
                <INHOMOGENEITY x="250" alpha_T="3.5" alpha_v0="0.4" />
                <INHOMOGENEITY x="370" alpha_T="3.5" alpha_v0="0.4" />
                <INHOMOGENEITY x="370" alpha_T="1.5" alpha_v0="0.9" />
            </FLOW_CONSERVING_INHOMOGENEITIES>
            <SPEED_LIMITS>
                <SPEED_LIMIT x="100" speedlimit_kmh="80" />
                <SPEED_LIMIT x="250" speedlimit_kmh="40" />
                <SPEED_LIMIT x="370" speedlimit_kmh="80" />
            </SPEED_LIMITS>
        </ROAD>
        <OUTPUT />
    </SIMULATION>
</SCENARIO>

**Comment by akegermany** [comment]
In this demo no file output is defined by purpose. This is an interactive simulation "game". If you want to modify the simulation config and generate csv output I recommend that you start with the two demo projects in sim/features/output. You can easily add the output config to your xprj xml file. 
By the way, the full syntax is defined in the xsd file 

xsd/src/main/resources/schema/MovsimScenario.xsd

(and the other xsd files there)
