### ISSUE TITLE
Changing simulations broken

### ISSUE THREAD

**Issue by superdyoll** [movsim/movsim#38]
It seems when you want to change from the simulation to one shown on the list or load one from the menu both are impossible. The file opener asks for an XML file which is not how projects are currently stored. The issue with loading the scenarios is that it calls reset, which calls initialise which try's to load the original project again, something about this is also broken.

I'm going through and trying to fix this although would like to know firstly if you're trying to transition to XML files or away from them so I can fix this correctly.

**Comment by akegermany** [comment]
thanks for pinpointing. Let me check first if we still want to have this. It's very old code and perhaps we can remove it. I'll come back soon.

**Comment by akegermany** [comment]
The viewer menu code is quite old. The File menu should be adapted to xprj simulation project files. And the Scenario menu (AppMenu.scenarioMenu) can be removed completely as it doesn't seem to be maintainable (too much hard-coded, relative paths to resources etc). 

@superdyoll What do you think?

**Comment by rgerm** [comment]
The faulty mechanism that led to loading to the scenario twice should be fixed. But as @akegermany  suggested, the "changing scenarios option" is also removed from the viewer. Could be reimplemented, but there is currently no real purpose for that.
