### ISSUE TITLE
Simulation runtime errors

### ISSUE THREAD

**Issue by MTGermany** [movsim/movsim#44]
I have tested all the provided projects (on Java 1.8) and found (mostly minor) errors:

(1) runtime error for all simulations which, however,
does not stop the simulation when running:

Exception in thread "main" java.lang.IllegalStateException: it's a mistake if this is set twice
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at org.movsim.simulator.SimulationRun.setCompletionCallback(SimulationRun.java:197)
	at org.movsim.viewer.ui.HighscoreFrame.<init>(HighscoreFrame.java:75)
	at org.movsim.viewer.ui.HighscoreFrame.initialize(HighscoreFrame.java:228)
	at org.movsim.viewer.ui.AppFrame.<init>(AppFrame.java:98)
	at org.movsim.viewer.App.main(App.java:67)

(2) Incorrect directory association for auxillary ressources such as images
when calling a project from another directory: it is attempted to get
the ressources from the simulation working directory (e.g.,
$movsimParent/movsim/testsim/) instead of from the movsim's ressources
(e.g., $movsimParent/sim/buildingBlocks/background_example.png)

 868 [main] ERROR (TrafficCanvas.java:initGraphicSettings:314) - cannot load background image background_example.png

(3) Following projects return errors without running at all (in all
other projects, the simulation runs even if errors are produced):

fail= consumption/data/sim/consumption_sim.xprj
consumption/data/ostfalia/consumption_ostfalia.xprj
sim/bookScenarioSimpleOnramp/onramp_KKW.xprj
sim/features/bidirectional/highway_intersection.xprj
sim/buildingBlocks/onramp.xprj

(4) In several projects, nothing can be seen (although the simulation
is running correctly) because the initial position/size settings do
not match the simulation region

**Comment by akegermany** [comment]
Hi Martin, regarding your points:
(1) I created the issue #46
(2) I cannot reproduce this, please be more specific, sim/buildingBlocks/trafficlight.xprj for example is loading a background image correctly as configured in the corresponding .properties 
(3.1) The consumption/ projects are working, read the README. They are used with the MovsimConsumption jar 
(3.2) onramp_KKW.xprj just had badly located detector cross-sections. I fixed that. However, I haven't checked which locations are actually intended.
(3.3) highway_intersection.xprj is not working. I removed it.
(3.4) onramp.xprj is fixed.

(4) I haven't found any example. 

Cheers,
Arne

**Comment by rgerm** [comment]
(3.4) The sim/buildingBlocks/onramp.xprj references

Scenario network_filename="onramp2.xodr"

but onramp2.xodr is not in the repository

**Comment by rgerm** [comment]
(4) all bookScenarioSimpleOnramp/onramp scenarios suffer from this. -> The y value in the simple_onramp.xodr should be adapted so that it is in the view.

**Comment by rgerm** [comment]
(2) I have the same behaviour as Martin. It works only if started within the directory where the file resides.

**Comment by rgerm** [comment]
(1) Appears only in the two games. Although the code in the HighScoreFrame is certainly not good, the Preconditions check in SimulationRun is causing problems instead of preventing. Why is it wrong to call the setter for the completion callback? If it is wrong it should not be exposed at all - it is already set in the ctor of the simulator.

**Comment by akegermany** [comment]
Thanks for the feedback. 
- I've fixed 3.4 - my local changes.
- For (4) I removed the obsolete properties. It is now centred correctly.

I'll also take a look at the issue things.

**Comment by MTGermany** [comment]
(2) even after I have changed the image path in the .properties file to the correct absolute path, it does not work for some reason. The error is as follows:
952 [main] ERROR (TrafficCanvas.java:initGraphicSettings:314) - cannot load background image /home2/treiber/versionedProjects/movsim/sim/buildingBlocks/background_example.png
 javax.imageio.IIOException: Can't read input file!

Nevertheless, this file exists (it shows the full moon surface distorted to a rectangle). I think the philosophy should be that all input files are fetched from the path given on the command line (this already works for the .xodr and .properties files), and the output files are all on the working directory (i.i., the directory where the simulation is started). The reason is that I do not want to clutter the (possibly versioned) demo directories with simulation output, so I use a different location (which may even be a different disk)

**Comment by akegermany** [comment]
Fixed (2) with 
commit 22d22840d42ecc9fde028358717998131dfd6310
Author: akegermany <mail@akesting.de>
Date:   Mon Sep 3 21:59:25 2018 +0200

    read background image from same path as project file (part of issue #44)
