### ISSUE TITLE
Fail to install on Windows

### ISSUE THREAD

**Issue by xiasun** [movsim/movsim#49]
Hi all,
I tried to install movsim on my Windows 7 machine, I have newly installed jdk-11.0.2 and maven-3.6.0. When runing `mvn clean install` on root dir of movsim, the following error message is shown:

---

[INFO] Compiling 16 source files to D:\movsim\xsd\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/movsim/xsd/src/main/java/org/movsim/simulator/vehicles/longitudinalm
odel/acceleration/parameter/IModelParameterOVMFVDM.java:[3,26] package org.movsim.
autogen does not exists
[ERROR] /D:/movsim/xsd/src/main/java/org/movsim/simulator/vehicles/longitudinalm
odel/acceleration/parameter/IModelParameterOVMFVDM.java:[13,5] fail to find symbol
  symbol:   class OptimalVelocityFunctionEnum
  position: interface org.movsim.simulator.vehicles.longitudinalmodel.acceleration.parame
ter.IModelParameterOVMFVDM
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for movsim 1.7.0-SNAPSHOT:
[INFO]
[INFO] movsim ............................................. SUCCESS [  0.802 s]
[INFO] MovsimXsd .......................................... FAILURE [  4.701 s]
[INFO] MovsimCommon ....................................... SKIPPED
[INFO] MovsimConsumption .................................. SKIPPED
[INFO] MovsimCore ......................................... SKIPPED
[INFO] MovsimViewer ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.740 s
[INFO] Finished at: 2019-01-20T17:46:33+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
7.0:compile (default-compile) on project MovsimXsd: Compilation failure: Compila
tion failure:
[ERROR] /D:/movsim/xsd/src/main/java/org/movsim/simulator/vehicles/longitudinalm
odel/acceleration/parameter/IModelParameterOVMFVDM.java:[3,26] package org.movsim.
autogen does not exists
[ERROR] /D:/movsim/xsd/src/main/java/org/movsim/simulator/vehicles/longitudinalm
odel/acceleration/parameter/IModelParameterOVMFVDM.java:[13,5] could not find ex
ternal symbol
[ERROR]   symbol:   class OptimalVelocityFunctionEnum
[ERROR]   position: interface org.movsim.simulator.vehicles.longitudinalmodel.acceleratio
n.parameter.IModelParameterOVMFVDM
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :MovsimXsd

---

I wonder is there anything I could do to locate the problem and solve it?
Thank you for your time!

**Comment by akegermany** [comment]
I tried with java 8 on windows and it worked fine. 
However, the last time I tried out java > 8 the dependencies weren't ready (the xsd project using jaxb is the tricky part, unfortunately).
However, now I got it to work with a java 11 version and the updated libraries.
I haven't tested on Windows yet but with a proper maven setup this should work as well.

Please try out and confirm that is working on windows too. 
A
