### ISSUE TITLE
Fail to run MovSimcore and MovSimVeiwer

### ISSUE THREAD

**Issue by beyond1self** [movsim/movsim#50]
command line: java -jar MovsimViewer-1.6.0-jar-with-dependencies.jar
error:
no log4j from commandline provided. Use default log4j configuration from=jar:file:/C:/Users/beyond1self/Desktop/movsim-Movsim-1.6.0/viewer/target/MovsimViewer-1.6.0-jar-with-dependencies.jar!/config/log4j.properties
No output path provided via option. Set output path to current directory!
0 [main] INFO  (FileUtils.java:dirExists:129) - dir exits: . exists!
No configuration file provided! Please specify a file via the option -f.

I can`t fix it , is there someone help me out?
thank you.

**Comment by akegermany** [comment]
The program expects some input configuration file. 
You find examples under movsim/sim/buildingBlocks

Invoking with -h gives you this:

java -jar MovsimViewer-1.7.0-SNAPSHOT-jar-with-dependencies.jar -h
no log4j from commandline provided. Use default log4j configuration from=jar:file:/home/kesting/workspace/movsim/viewer/target/MovsimViewer-1.7.0-SNAPSHOT-jar-with-dependencies.jar!/config/log4j.properties
option -h. Exit Programm
usage: movsim
 -d,--write_dot                  writes a 'dot' network file for further
                                 analysis of the xodr
 -f,--file <arg>                 movsim main configuration file (ending
                                 ".xprj" will be added automatically if
                                 not provided.
 -h,--help                       prints this message
 -l,--log                        writes the file "log4j.properties" to
                                 file to adjust the logging properties on
                                 an individual level
 -o,--directory <arg>            argument is the output path relative to
                                 calling directory
 -s,--simulation scanning mode   invokes the simulator repeatedly in a
                                 loop (needs to be programmed by user)
 -v,--validate                   parses xml input file for validation
                                 (without simulation)
 -w,--write_xsd                  writes xsd file to output (for
                                 convenience/lookup schema definitions)
